class AppText {
  AppText(this.languageCode);

  final String languageCode;

  static const Map<String, Map<String, String>> _values = {
    'id': {
      'app_title': 'Ve-Wallet',
      'settings': 'Pengaturan',
      'personal_info': 'Informasi Pribadi',
      'security': 'Keamanan',
      'notifications': 'Notifikasi',
      'shared_account': 'Shared Account',
      'transaction_categories': 'Kategori Transaksi',
      'language': 'Bahasa',
      'theme': 'Tema Visual',
      'help_center': 'Pusat Bantuan',
      'daily_tips': 'Tips Harian',
      'account_security_group': 'Akun & Keamanan',
      'app_preferences_group': 'Preferensi Aplikasi',
      'developer_group': 'Pengembang',
      'logout': 'Keluar dari Akun',
      'security_subtitle': 'Sandi, PIN, dan biometrik',
      'language_subtitle_id': 'Indonesia',
      'language_subtitle_en': 'Inggris',
      'theme_subtitle_light': 'Terang',
      'theme_subtitle_dark': 'Gelap',
      'theme_subtitle_system': 'Sistem',
      'admin_mode': 'Mode Admin',
      'enable_admin_features': 'Aktifkan akses fitur admin',
      'save': 'Simpan',
      'apply_preferences': 'Terapkan Preferensi',
      'password': 'Sandi',
      'change_password': 'Ganti Sandi',
      'old_password': 'Sandi lama',
      'new_password': 'Sandi baru',
      'confirm_password': 'Konfirmasi sandi baru',
      'app_pin': 'PIN Aplikasi',
      'set_pin': 'Atur PIN',
      'change_pin': 'Ubah PIN',
      'verify_pin': 'Verifikasi PIN',
      'biometric': 'Biometrik',
      'enable_biometric': 'Aktifkan biometrik',
      'disable_biometric': 'Nonaktifkan biometrik',
      'pin_hint': 'PIN 4-6 digit',
      'security_settings_title': 'Keamanan',
      'security_card_title': 'Proteksi akun',
      'security_card_body':
          'Kelola sandi, PIN, dan biometrik untuk menjaga akses akun tetap aman.',
      'success_password_changed': 'Sandi berhasil diperbarui',
      'success_pin_saved': 'PIN berhasil disimpan',
      'success_pin_disabled': 'PIN berhasil dinonaktifkan',
      'success_biometric_updated': 'Preferensi biometrik berhasil diperbarui',
      'pin_verified': 'PIN sesuai',
      'loading': 'Memuat...',
      'cancel': 'Batal',
      'verify': 'Verifikasi',
      'turn_off': 'Matikan',
      'turn_on': 'Aktifkan',
      'current_language': 'Bahasa aktif',
      'current_theme': 'Tema aktif',
      'indonesian': 'Indonesia',
      'english': 'Inggris',
      'light_mode': 'Terang',
      'dark_mode': 'Gelap',
      'system_mode': 'Ikuti sistem',
      'admin_profile': 'Profil Admin',
      'edit_profile': 'Edit Profil',
      'security_preferences': 'Keamanan & Preferensi',
      'switch_to_user_mode': 'Switch ke Mode User',
      'switch_to_user_mode_subtitle':
          'Beralih ke antarmuka pengguna biasa untuk simulasi pengalaman user.',
      'manage_security_preferences':
          'Kelola sandi, PIN, biometrik, bahasa, dan tema akun admin.',
      'personal_info_subtitle': 'Nama, email, dan biodata',
      'notifications_subtitle': 'Atur pemberitahuan Anda',
      'shared_account_subtitle': 'Kelola akun bersama',
      'categories_subtitle': 'Atur kategori pemasukan & pengeluaran',
      'help_center_subtitle': 'Tanya jawab dan dukungan',
      'tips_subtitle': 'Insight singkat biar keputusan keuangan lebih rapi',
      'admin_system_management': 'Manajemen Sistem',
      'admin_mode_navigation': 'Navigasi Mode',
      'edit_profile_subtitle': 'Ubah nama dan avatar akun yang sedang dipakai.',
      'admin_notifications_subtitle':
          'Lihat notifikasi sistem dan aktivitas akun admin.',
      'admin_help_subtitle':
          'Buka panduan penggunaan dan catatan penting aplikasi.',
      'today_priority': 'Prioritas Hari Ini',
      'operational_checklist': 'Checklist Operasional',
      'security_status': 'Status keamanan',
      'security_updated_automatically': 'Terakhir diperbarui: otomatis',
      'no_users_to_analyze': 'Belum ada data user untuk dianalisis.',
      'active_users_summary':
          'Monitoring aktif. {active} dari {total} user terdeteksi aktif hari ini.',
      'registered_users': '{count} user terdaftar',
      'registered_users_subtitle':
          'Total akun yang saat ini tercatat di sistem.',
      'active_users_today': '{count} user aktif hari ini',
      'active_users_today_subtitle':
          'Diukur dari aktivitas masuk terbaru pengguna hari ini.',
      'transactions_recorded': '{count} transaksi tercatat',
      'transactions_recorded_subtitle':
          'Jumlah transaksi yang sudah tercatat di aplikasi.',
      'admin_access': 'Akses admin',
      'admin_access_detail':
          'Panel ini hanya bisa dibuka oleh akun yang memiliki akses admin.',
      'active_households': 'Household aktif',
      'active_households_detail': '{count} household saat ini aktif di aplikasi.',
      'recent_activity': 'Aktivitas terbaru',
      'recent_activity_detail':
          '{count} log terbaru tersedia di menu History untuk audit cepat.',
      'new_password_min_length': 'Sandi baru minimal 8 karakter',
      'password_confirmation_mismatch': 'Konfirmasi sandi tidak sama',
      'pin_length_error': 'PIN harus 4 sampai 6 digit',
      'pin_confirmation_mismatch': 'Konfirmasi PIN tidak sama',
      'pin_old_mismatch': 'PIN lama tidak sesuai',
      'password_change_failed': 'Gagal mengganti sandi: {error}',
      'pin_change_failed': 'Gagal mengubah PIN: {error}',
      'pin_save_failed': 'Gagal menyimpan PIN: {error}',
      'biometric_change_failed': 'Gagal mengubah biometrik: {error}',
      'biometric_access_failed': 'Gagal mengakses biometrik: {error}',
      'save_language_failed': 'Gagal menyimpan bahasa: {error}',
      'save_theme_failed': 'Gagal menyimpan tema: {error}',
      'unlock_with_pin': 'Masukkan PIN untuk melanjutkan',
      'unlock_with_biometric_or_pin':
          'Verifikasi biometrik atau masukkan PIN untuk melanjutkan',
      'biometric_not_available': 'Biometrik tidak tersedia di perangkat ini',
      'biometric_cancelled': 'Verifikasi biometrik dibatalkan',
      'pin_invalid': 'PIN tidak sesuai',
    },
    'en': {
      'app_title': 'Ve-Wallet',
      'settings': 'Settings',
      'personal_info': 'Personal Info',
      'security': 'Security',
      'notifications': 'Notifications',
      'shared_account': 'Shared Account',
      'transaction_categories': 'Transaction Categories',
      'language': 'Language',
      'theme': 'Visual Theme',
      'help_center': 'Help Center',
      'daily_tips': 'Daily Tips',
      'account_security_group': 'Account & Security',
      'app_preferences_group': 'App Preferences',
      'developer_group': 'Developer',
      'logout': 'Sign Out',
      'security_subtitle': 'Password, PIN, and biometrics',
      'language_subtitle_id': 'Indonesian',
      'language_subtitle_en': 'English',
      'theme_subtitle_light': 'Light',
      'theme_subtitle_dark': 'Dark',
      'theme_subtitle_system': 'System',
      'admin_mode': 'Admin Mode',
      'enable_admin_features': 'Enable admin-only features',
      'save': 'Save',
      'apply_preferences': 'Apply Preference',
      'password': 'Password',
      'change_password': 'Change Password',
      'old_password': 'Current password',
      'new_password': 'New password',
      'confirm_password': 'Confirm new password',
      'app_pin': 'App PIN',
      'set_pin': 'Set PIN',
      'change_pin': 'Change PIN',
      'verify_pin': 'Verify PIN',
      'biometric': 'Biometrics',
      'enable_biometric': 'Enable biometrics',
      'disable_biometric': 'Disable biometrics',
      'pin_hint': '4-6 digit PIN',
      'security_settings_title': 'Security',
      'security_card_title': 'Account protection',
      'security_card_body':
          'Manage password, PIN, and biometrics to keep account access secure.',
      'success_password_changed': 'Password updated successfully',
      'success_pin_saved': 'PIN saved successfully',
      'success_pin_disabled': 'PIN disabled successfully',
      'success_biometric_updated': 'Biometric preference updated successfully',
      'pin_verified': 'PIN verified',
      'loading': 'Loading...',
      'cancel': 'Cancel',
      'verify': 'Verify',
      'turn_off': 'Disable',
      'turn_on': 'Enable',
      'current_language': 'Current language',
      'current_theme': 'Current theme',
      'indonesian': 'Indonesian',
      'english': 'English',
      'light_mode': 'Light',
      'dark_mode': 'Dark',
      'system_mode': 'Follow system',
      'admin_profile': 'Admin Profile',
      'edit_profile': 'Edit Profile',
      'security_preferences': 'Security & Preferences',
      'switch_to_user_mode': 'Switch to User Mode',
      'switch_to_user_mode_subtitle':
          'Switch to the regular user interface to simulate the user experience.',
      'manage_security_preferences':
          'Manage password, PIN, biometrics, language, and theme for the admin account.',
      'personal_info_subtitle': 'Name, email, and profile details',
      'notifications_subtitle': 'Manage your alerts',
      'shared_account_subtitle': 'Manage your shared account',
      'categories_subtitle': 'Manage income and expense categories',
      'help_center_subtitle': 'FAQ and support',
      'tips_subtitle': 'Short insights to keep money decisions sharper',
      'admin_system_management': 'System Management',
      'admin_mode_navigation': 'Mode Navigation',
      'edit_profile_subtitle': 'Update the current account name and avatar.',
      'admin_notifications_subtitle':
          'Review system notifications and admin activity.',
      'admin_help_subtitle':
          'Open usage guidance and important app notes.',
      'today_priority': 'Today Priorities',
      'operational_checklist': 'Operational Checklist',
      'security_status': 'Security status',
      'security_updated_automatically': 'Last updated: automatic',
      'no_users_to_analyze': 'No user data is available yet.',
      'active_users_summary':
          'Monitoring is active. {active} of {total} users were active today.',
      'registered_users': '{count} registered users',
      'registered_users_subtitle':
          'Total accounts currently recorded in the system.',
      'active_users_today': '{count} active users today',
      'active_users_today_subtitle':
          'Measured from the latest sign-in activity today.',
      'transactions_recorded': '{count} recorded transactions',
      'transactions_recorded_subtitle':
          'Total transactions currently stored in the app.',
      'admin_access': 'Admin access',
      'admin_access_detail':
          'This panel can only be opened by accounts with admin access.',
      'active_households': 'Active households',
      'active_households_detail': '{count} households are active in the app.',
      'recent_activity': 'Recent activity',
      'recent_activity_detail':
          '{count} latest logs are available in History for quick audit.',
      'new_password_min_length': 'New password must be at least 8 characters',
      'password_confirmation_mismatch':
          'Password confirmation does not match',
      'pin_length_error': 'PIN must be 4 to 6 digits',
      'pin_confirmation_mismatch': 'PIN confirmation does not match',
      'pin_old_mismatch': 'Current PIN does not match',
      'password_change_failed': 'Failed to change password: {error}',
      'pin_change_failed': 'Failed to update PIN: {error}',
      'pin_save_failed': 'Failed to save PIN: {error}',
      'biometric_change_failed': 'Failed to update biometrics: {error}',
      'biometric_access_failed': 'Failed to access biometrics: {error}',
      'save_language_failed': 'Failed to save language: {error}',
      'save_theme_failed': 'Failed to save theme: {error}',
      'unlock_with_pin': 'Enter your PIN to continue',
      'unlock_with_biometric_or_pin':
          'Use biometrics or enter your PIN to continue',
      'biometric_not_available': 'Biometrics are not available on this device',
      'biometric_cancelled': 'Biometric verification was cancelled',
      'pin_invalid': 'PIN does not match',
    },
  };

  String call(String key) {
    return _values[languageCode]?[key] ?? _values['id']![key] ?? key;
  }

  String format(String key, Map<String, Object?> values) {
    var result = call(key);
    values.forEach((placeholder, value) {
      result = result.replaceAll('{$placeholder}', '$value');
    });
    return result;
  }
}
